### ISSUE TITLE
[Question] How did you manage to get assets?

### ISSUE THREAD

**Issue by teslabyte** [CosmicTraveler/CosmicTraveler.github.io#1]
They are encrypted when installed on a device.

**Comment by CosmicTraveler** [comment]
from bilibili

**Comment by CosmicTraveler** [comment]
> 
> 
> They are encrypted when installed on a device.

from bilibili

**Comment by teslabyte** [comment]
Could you send me a link if you have one? Here or on Discord (Satoru#1129), either works

**Comment by CosmicTraveler** [comment]
> 
> 
> Could you send me a link if you have one? Here or on Discord (Satoru#1129), either works

https://wiki.biligame.com/zspms/%E6%AD%A6%E5%99%A8

**Comment by CosmicTraveler** [comment]
> 
> 
> Could you send me a link if you have one? Here or on Discord (Satoru#1129), either works

https://wiki.biligame.com/zspms/武器
